### ISSUE TITLE
dynamic reconfigure in ROS noetic - missing import

### ISSUE THREAD

**Issue by Petros626** [jsk-ros-pkg/coral_usb_ros#118]
Hey,

After I installed EdgeTPU, tflite_runtime etc. My IDE shows me, that the `coral_usb.cfg` cannot be imported. I searched through the old issues, but found only attempts for older ROS versions.

The community says it's more an bug than an error.

![Screenshot from 2022-07-12 15-20-31](https://user-images.githubusercontent.com/62354721/178500341-d830abda-952a-46ce-ac6e-faddb7dcbb04.png)

**Comment by knorth55** [comment]
and check your editor's python import linter.
does the  linter check ROS python path?
you should simply try running `import coral_usb.cfg` in `ipython3` after sourcing the workspace.

**Comment by Petros626** [comment]
I will try it and let you know, if it helps

**Comment by Petros626** [comment]
Hey so I tried with the given instructions and it works, the problem is that my LiDAR driver isn't happy with `catkin_build `and I could not solve the error (CMAKELISTS can't be build).
```
git clone https://github.com/jsk-ros-pkg/coral_usb_ros.git
wstool init
wstool merge coral_usb_ros/fc.rosinstall
wstool update
rosdep install --from-paths . --ignore-src -y -r
cd ~/coral_ws <--- my named catkin_ws
catkin init
catkin build
```
So I would like to know why, the node can't be build with `catkin_make,` it shows me, that the package is not found by catkin.
