### ISSUE TITLE
catkin_make instead of catkin build failed

### ISSUE THREAD

**Issue by Petros626** [jsk-ros-pkg/coral_usb_ros#119]
Hey @knorth55  so I tried with the given instructions (**Workspace build (Noetic)**) and it works, the problem is that my LiDAR driver isn't happy (don't work) with `catkin build `and I could not solve the error (CMAKELISTS can't be build).

![Screenshot from 2022-07-15 09-37-28](https://user-images.githubusercontent.com/62354721/179175734-dfb8d7e5-5aad-4595-b875-d4b6f5402557.png)

After adding the required folder

![Screenshot from 2022-07-15 09-51-02](https://user-images.githubusercontent.com/62354721/179178699-230e60db-4fe9-426e-bc35-88a069786b62.png)

So I would like to know why, the node can't be build with `catkin_make`.

**Comment by knorth55** [comment]
please check if you use the latest master branch.
Also, please use catkin, instead of cakin_build.

**Comment by Petros626** [comment]
I use `catkin_make` instead of `catkin_build`. I was able to fix some other warnings and finally end up with this one. Normally if you clone the repo the lastest version must be downloaded? I will clone the `[0.0.10: 11th release]` and let you know.

![Screenshot from 2022-07-19 07-54-42](https://user-images.githubusercontent.com/62354721/179675859-249483a0-87e6-4c62-b256-092a668fe8ef.png)

**Comment by knorth55** [comment]
how about `catkin`? 
please install `python3-catkin-tools` and clean up workspace and run `catkin build`.
also please copy and paste all the error output of the build.

**Comment by Petros626** [comment]
`If you rely on a stable environment, please use catkin_make instead of this tool` according to information. I mentioned it in the old issue, that catkin_build fails with the LiDAR driver and I need it.
I will cleanup again the workspace and send you the whole build process message.

**Comment by knorth55** [comment]
@Petros626 I confirmed the issue with `catkin_make`.
And I found this is `catkin_virutalenv` issue.
I solved the issue in https://github.com/locusrobotics/catkin_virtualenv/pull/88.
Can you clone `catkin_virtualenv` with this PR in to your workspace?

**Comment by knorth55** [comment]
Also your lidar package should be build with `catkin build`.
Maybe `CMakeLists.txt` of the package might be wrong.
If you can tell me the package name, I will take a look.

**Comment by Petros626** [comment]
> Also your lidar package should be build with `catkin build`. Maybe `CMakeLists.txt` of the package might be wrong. If you can tell me the package name, I will take a look.

I will try the way I have on my mind and then I will see further. The package I use is: https://github.com/yujinrobot/yujin_lidar_v2

**Comment by knorth55** [comment]
> I will try the way I have on my mind and then I will see further. The package I use is: [yujinrobot/yujin_lidar_v2](https://github.com/yujinrobot/yujin_lidar_v2)

Weird... I could build the pacakge with `catkin build`.

```bash
cd /tmp
git clone https://github.com/yujinrobot/yujin_lidar_v2.git
mkdir catkin_ws/src -p
cd catkin_ws/src
ln -sf /tmp/yujin_lidar_v2/driver_ros1_noetic_ubuntu2004 .
cd ../
catkin build
```

**Comment by Petros626** [comment]
> > I will try the way I have on my mind and then I will see further. The package I use is: [yujinrobot/yujin_lidar_v2](https://github.com/yujinrobot/yujin_lidar_v2)
> 
> Weird... I could build the pacakge with `catkin build`.
> 
> ```shell
> cd /tmp
> git clone https://github.com/yujinrobot/yujin_lidar_v2.git
> mkdir catkin_ws/src -p
> cd catkin_ws/src
> ln -sf /tmp/yujin_lidar_v2/driver_ros1_noetic_ubuntu2004 .
> cd ../
> catkin build
> ```

hmm okay, I will see today if it's working and then post my solution for this issue in my case.

**Comment by Petros626** [comment]
> @Petros626 I confirmed the issue with `catkin_make`. And I found this is `catkin_virutalenv` issue.
> 
> I solved the issue in [locusrobotics/catkin_virtualenv#88](https://github.com/locusrobotics/catkin_virtualenv/pull/88). Can you clone `catkin_virtualenv` with this PR in to your workspace? In my environment, with [locusrobotics/catkin_virtualenv#88](https://github.com/locusrobotics/catkin_virtualenv/pull/88), I can successfully build the workspace by `catkin_make`.

Solved it!
