### ISSUE TITLE
node publishes faster than receiving messages?

### ISSUE THREAD

**Issue by Petros626** [jsk-ros-pkg/coral_usb_ros#121]
Hey,

I experienced the weird behaviour, that the topic `/output/image` is published faster than receiving the topic `/sensor_msgs/Image`. I thought the incoming message rate would specify how fast the image is published?
Any idea if it belongs to the node?

Input: Output
sensor/msgs_Image (every 2 sec.) -> coral usb node -> edgetpu_object_detector/output/image (every 0.5/1 sec.)

**Comment by knorth55** [comment]
https://github.com/jsk-ros-pkg/coral_usb_ros#parameters

`visualization` loop is anothr loop.
we can control the hz by  `visualization_duration`.

**Comment by Petros626** [comment]
> https://github.com/jsk-ros-pkg/coral_usb_ros#parameters
> 
> `visualization` loop is anothr loop. we can control the hz by `visualization_duration`.

the visualization frequency in rviz is the same the messages are coming (2 Hz). By using using `rostopic echo /edgetpu_object_detector/output/image` I noticed the difference from 2Hz to >2Hz.

Your suggestions works good with a value of `2.0`, but it wonders me, how the node could `echo` the pixel values faster than the incoming `Image message`...

**Comment by knorth55** [comment]
> Your suggestions works good with a value of 2.0, but it wonders me, how the node could echo the pixel values faster than the incoming Image message...

The node just keep the old image and use it to publish in >2Hz.

**Comment by Petros626** [comment]
Yes, but your suggestion helps, will close the issue
